version: '3.8'

services:

  # L'application principale Fair Hire
  app:
    build: .
    container_name: fair-hire-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      - mlflow
    env_file:
      - .env

  # Tracking des exp√©riences MLflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: fair-hire-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow